[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.well-known/appspecific/com.tesla.3p.public-key.pem"
  [headers.values]
    Content-Type = "application/x-pem-file"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://api.stripe.com; frame-src https://js.stripe.com;"

# Redirect rules for SPA routing

# Map specific Tesla public key (renamed to avoid .pem removal)
[[redirects]]
  from = "/.well-known/appspecific/com.tesla.3p.public-key.pem"
  to = "/wellknown/appspecific/com.tesla.3p.public-key.txt"
  status = 200
  force = true

# Map other .well-known requests to wellknown directory
[[redirects]]
  from = "/.well-known/*"
  to = "/wellknown/:splat"
  status = 200

[[redirects]]
  from = "/verify/*"
  to = "/verify/[id]"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { "path" = "!/.*\\..*$/" } 